### PR TITLE
Azure Docs

### PR DESCRIPTION
**Pull request by abibat-adesina**
Creating placeholders for Azure documentation

### CODE REVIEW

**Comment by wrnu** [comment]
I just received a question from a early adopter:

>have a question regarding Azure, I am hoping you can help!
We got our  landing zone, and I have started experimenting with it. 
I have created a VM on our Azure landing zone, which I do not need anymore, but it won't let me delete it!
Any idea how I can delete this resource that I created?
I am not deleting the network, so not sure why is this happening!

The solution, and my response was:

>just remove the networking lock, you should have perms
 anytime our automation runs it will put it back but you can remove it when you need to
 
 We should add something to the networking and be-mindful pages

**Review by wrnu — APPROVED** [review]

**Comment by wrnu** [comment]
Hi @Pilargit12 

This is a significant refactor of our public cloud docs that add our Azure Docs. We've moved cloud specific docs under AWS, and Azure, Sub pages. Please let me know if you have any questions.

**Comment by Pilargit12** [comment]
Hi @wrnu and @abibat-adesina ! Thank you for sending this through.  This is a major review to a new pages so I will need to review them by using Visual Studio code and update this PR again instead of doing it through the usual GitHub review. 

I have the following comments/questions: 

 1. Do you have any further developments to the content of this PR as it is currently? The reason I ask is because we cannot be working on the same document at the same time while I am reviewing the content. 
 
 2. If you are ok with me working on this now (No further updates until I am done updating the PR), I can start reviewing the content, but we will not be able to publish until after the interregnum period which started last September 21 and runs until a new cabinet is sworn in (Sometime in November, exact date isn't known) 
 
 Can you confirm the above?  - Thank you so much!

**Comment by wrnu** [comment]
@Pilargit12 We will freeze updates to this PR. Please go ahead and work on this branch/PR. Thanks!

**Comment by Pilargit12** [comment]
Hi @wrnu - I have updated a new update PR. 

 
- I made a few changes with name of sections such as the "Getting started" in each Azure and AWS section with "Getting started with AWS" / "Getting started with Azure" and updated the initial "getting started (general) with a "Welcome" instead
- A few changes in headings to keep sentence case  in consideration for new or updates to documents: **G**etting **S**tarted to "**G**etting **s**tarted..."
- It would be great if you could have another look, when ready feel free to send back for a final review too
- Please do not merge to main due to interregnum, I will advise as soon as I know when we are allowed to publish new material 

Thank you!

**Comment by Pilargit12** [comment]
Hi @abibat-adesina, @wrnu - Interregnum has now ended and we can publish the tech docs after another person has reviewed the latest PR update.  Thank you, please let me know if you have any questions!

**Review by harsimranmaan — APPROVED** [review]

**Pull request merged**
