### PR TITLE
Add edit button to docs pages

### PR DESCRIPTION
**Pull request by MonicaG**
Updated mkdocs file to include option to display the edit button. This will allow a user to open a GitHub issue or PR for a given page so they can suggest updates.

### CODE REVIEW

**Review by Pilargit12 — COMMENTED** [review]
Will leave this to @MaxWardle for full approval! Thank you!

**Comment by MonicaG** [comment]
Hi @MaxWardle - Just following up on this. Are these changes ok? Can they be merged? Thank you!

**Comment by MaxWardle** [comment]
> Hi @MaxWardle - Just following up on this. Are these changes ok? Can they be merged? Thank you!

Hi @MonicaG just had a question about the changes in the comment above, do you know how the edit_uri field works? Should we be referencing the "dev" branch? Do other teams reference their "main" branch? Just trying to follow proper CI/CD here but unsure what the norm is for community edits. Thanks!

**Comment by MonicaG** [comment]
Hi @MaxWardle - Other teams are using the main branch. The edit_uri field should point to the branch that has the production code.

 I set the edit_uri field to the 'dev' branch because that is set as the default branch on this repo. But I can change it to another branch.

**Review by MaxWardle — APPROVED** [review]
After confirming the main branch is correct, looks good to merge.

**Pull request merged**
