### PR TITLE
Add quicksight doc

### PR DESCRIPTION
**Pull request by abibat-adesina**

### CODE REVIEW

**Comment by MaxWardle** [comment]
> Hi Abi, I updated the PR last Thursday - should be good to go. @MaxWardle I am not sure where this page would fall under, what category?

Hi @Pilargit12, I put this page at the bottom of build and deploy an app, but it may constitute a new category? We could re-visit the private cloud team's menu structure, although it may also look strange if this page is the only thing in the new section? Let me know what you think.

**Comment by Pilargit12** [comment]
Hi @MaxWardle - I think it would be worth to revisit the categories and plans for new pages for now let's keep it there. But I am wondering if a new category should be dedicated for Platform Product Registry management ?

**Comment by MaxWardle** [comment]
> Hi @MaxWardle - I think it would be worth to revisit the categories and plans for new pages for now let's keep it there. But I am wondering if a new category should be dedicated for Platform Product Registry management ?

Alright sounds good, I will approve this for now then, and let's have that chat in the future then. I think a app maintenance section sounds like a good idea.

**Review by MaxWardle — APPROVED** [review]
Looks good to me as per the comments above.

**Pull request merged**
